

// Autosnake:
// a snake wanders around a ring (head green, tail türkis?), must reach next item as fast as possible
// items are being placed here and there, snake must reach them as fast as possible (left or right...)
// snake overlaps items?
// snake cannot hit itself?

// timer: for each aim there's a minimum distance to be travelled. After the distance, there's a countdown for each
// step taken. After 12 such steps, the game is over!


~game = Snake1d();